<?xml version="1.0"?>
<robot name="graphRobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- INCLUDES -->
    <xacro:include filename="commom_properties.xacro"/>
    <xacro:include filename="dimensions.xacro"/>
    <xacro:include filename="mobile_base_gazebo.xacro"/>


    <!-- WHEEL MACRO (ONLY radius, distance from center and angle in degrees) -->
    <xacro:macro name="add_wheel" params="wheel_name radius distance deg">

        <xacro:property name="rad" value="${deg * pi/180.0}"/>
        <xacro:property name="x" value="${distance * cos(rad)}"/>
        <xacro:property name="y" value="${distance * sin(rad)}"/>
        <xacro:property name="z" value="0"/>

        <xacro:property name="pitch" value="1.57"/>

        <link name="${wheel_name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="0.05"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 ${pitch} 0"/>
                <material name="grey"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="0.05"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 ${pitch} 0"/>
            </collision>

            <inertial>
                <mass value="0.5"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>

        <joint name="${wheel_name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_link"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 ${rad}"/>
            <axis xyz="0 1 0"/>
        </joint>

    </xacro:macro>


    <!-- BASE -->
    <link name="base_footprint"/>


        <gazebo>
        <plugin name="gz::sim::systems::PosePublisher"
                filename="gz-sim-pose-publisher-system">
            <update_frequency>10</update_frequency>
            <publish_model_pose>true</publish_model_pose>
            <publish_link_pose>false</publish_link_pose>
            <use_pose_vector_msg>true</use_pose_vector_msg>
        </plugin>
        </gazebo>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertia
            m="1.0"
            r="${base_radius}"
            h="${base_height}"
            xyz="0 0 ${base_height/2}"
            rpy="0 0 0"/>
    </link>


    <!-- 3 WHEELS DEFINED USING POLAR COORDINATES -->
    <xacro:add_wheel wheel_name="wheel_front"  radius="0.1" distance="0.55" deg="90"/>
    <xacro:add_wheel wheel_name="wheel_left"   radius="0.1" distance="0.55" deg="210"/>
    <xacro:add_wheel wheel_name="wheel_right"  radius="0.1" distance="0.55" deg="330"/>

</robot>
